/* This file is generated by scripts/generate-token-module.mjs. */
import type { ComponentTokenDefinition, PrimitiveTokenDefinition, SemanticTokenDefinition } from './types.js';

export const tokenContractVersion = 1 as const;
export const primitiveTokens = [
  {
    "name": "color.neutral.0",
    "type": "color",
    "value": "#ffffff",
    "cssVariable": "--csn-ref-color-neutral-0",
    "description": "Lightest neutral reference color."
  },
  {
    "name": "color.neutral.50",
    "type": "color",
    "value": "#f8fafc",
    "cssVariable": "--csn-ref-color-neutral-50",
    "description": "Very light neutral reference color."
  },
  {
    "name": "color.neutral.100",
    "type": "color",
    "value": "#f1f5f9",
    "cssVariable": "--csn-ref-color-neutral-100",
    "description": "Light neutral reference color."
  },
  {
    "name": "color.neutral.200",
    "type": "color",
    "value": "#e2e8f0",
    "cssVariable": "--csn-ref-color-neutral-200",
    "description": "Soft neutral reference color."
  },
  {
    "name": "color.neutral.300",
    "type": "color",
    "value": "#cbd5e1",
    "cssVariable": "--csn-ref-color-neutral-300",
    "description": "Mid-light neutral reference color."
  },
  {
    "name": "color.neutral.500",
    "type": "color",
    "value": "#64748b",
    "cssVariable": "--csn-ref-color-neutral-500",
    "description": "Mid neutral reference color."
  },
  {
    "name": "color.neutral.700",
    "type": "color",
    "value": "#334155",
    "cssVariable": "--csn-ref-color-neutral-700",
    "description": "Dark neutral reference color."
  },
  {
    "name": "color.neutral.900",
    "type": "color",
    "value": "#0f172a",
    "cssVariable": "--csn-ref-color-neutral-900",
    "description": "Very dark neutral reference color."
  },
  {
    "name": "color.neutral.1000",
    "type": "color",
    "value": "#000000",
    "cssVariable": "--csn-ref-color-neutral-1000",
    "description": "Darkest neutral reference color."
  },
  {
    "name": "color.brand.50",
    "type": "color",
    "value": "#eff6ff",
    "cssVariable": "--csn-ref-color-brand-50",
    "description": "Light brand reference color."
  },
  {
    "name": "color.brand.100",
    "type": "color",
    "value": "#dbeafe",
    "cssVariable": "--csn-ref-color-brand-100",
    "description": "Soft brand reference color."
  },
  {
    "name": "color.brand.500",
    "type": "color",
    "value": "#2563eb",
    "cssVariable": "--csn-ref-color-brand-500",
    "description": "Primary brand reference color."
  },
  {
    "name": "color.brand.600",
    "type": "color",
    "value": "#1d4ed8",
    "cssVariable": "--csn-ref-color-brand-600",
    "description": "Strong brand reference color."
  },
  {
    "name": "color.brand.700",
    "type": "color",
    "value": "#1e40af",
    "cssVariable": "--csn-ref-color-brand-700",
    "description": "Dark brand reference color."
  },
  {
    "name": "color.red.50",
    "type": "color",
    "value": "#fef2f2",
    "cssVariable": "--csn-ref-color-red-50",
    "description": "Light danger reference color."
  },
  {
    "name": "color.red.500",
    "type": "color",
    "value": "#dc2626",
    "cssVariable": "--csn-ref-color-red-500",
    "description": "Danger reference color."
  },
  {
    "name": "color.red.700",
    "type": "color",
    "value": "#b91c1c",
    "cssVariable": "--csn-ref-color-red-700",
    "description": "Strong danger reference color."
  },
  {
    "name": "color.green.50",
    "type": "color",
    "value": "#f0fdf4",
    "cssVariable": "--csn-ref-color-green-50",
    "description": "Light success reference color."
  },
  {
    "name": "color.green.500",
    "type": "color",
    "value": "#16a34a",
    "cssVariable": "--csn-ref-color-green-500",
    "description": "Success reference color."
  },
  {
    "name": "color.green.700",
    "type": "color",
    "value": "#15803d",
    "cssVariable": "--csn-ref-color-green-700",
    "description": "Strong success reference color."
  },
  {
    "name": "color.amber.50",
    "type": "color",
    "value": "#fffbeb",
    "cssVariable": "--csn-ref-color-amber-50",
    "description": "Light warning reference color."
  },
  {
    "name": "color.amber.500",
    "type": "color",
    "value": "#d97706",
    "cssVariable": "--csn-ref-color-amber-500",
    "description": "Warning reference color."
  },
  {
    "name": "color.amber.700",
    "type": "color",
    "value": "#b45309",
    "cssVariable": "--csn-ref-color-amber-700",
    "description": "Strong warning reference color."
  },
  {
    "name": "space.0",
    "type": "dimension",
    "value": "0",
    "cssVariable": "--csn-ref-space-0",
    "description": "Zero spacing reference."
  },
  {
    "name": "space.1",
    "type": "dimension",
    "value": "0.25rem",
    "cssVariable": "--csn-ref-space-1",
    "description": "Extra-small spacing reference."
  },
  {
    "name": "space.2",
    "type": "dimension",
    "value": "0.5rem",
    "cssVariable": "--csn-ref-space-2",
    "description": "Small spacing reference."
  },
  {
    "name": "space.3",
    "type": "dimension",
    "value": "0.75rem",
    "cssVariable": "--csn-ref-space-3",
    "description": "Compact spacing reference."
  },
  {
    "name": "space.4",
    "type": "dimension",
    "value": "1rem",
    "cssVariable": "--csn-ref-space-4",
    "description": "Base spacing reference."
  },
  {
    "name": "space.5",
    "type": "dimension",
    "value": "1.25rem",
    "cssVariable": "--csn-ref-space-5",
    "description": "Medium spacing reference."
  },
  {
    "name": "space.6",
    "type": "dimension",
    "value": "1.5rem",
    "cssVariable": "--csn-ref-space-6",
    "description": "Large spacing reference."
  },
  {
    "name": "space.8",
    "type": "dimension",
    "value": "2rem",
    "cssVariable": "--csn-ref-space-8",
    "description": "Extra-large spacing reference."
  },
  {
    "name": "space.10",
    "type": "dimension",
    "value": "2.5rem",
    "cssVariable": "--csn-ref-space-10",
    "description": "Section spacing reference."
  },
  {
    "name": "space.12",
    "type": "dimension",
    "value": "3rem",
    "cssVariable": "--csn-ref-space-12",
    "description": "Large section spacing reference."
  },
  {
    "name": "radius.none",
    "type": "dimension",
    "value": "0",
    "cssVariable": "--csn-ref-radius-none",
    "description": "Square corner reference."
  },
  {
    "name": "radius.sm",
    "type": "dimension",
    "value": "0.25rem",
    "cssVariable": "--csn-ref-radius-sm",
    "description": "Small corner radius reference."
  },
  {
    "name": "radius.md",
    "type": "dimension",
    "value": "0.5rem",
    "cssVariable": "--csn-ref-radius-md",
    "description": "Medium corner radius reference."
  },
  {
    "name": "radius.lg",
    "type": "dimension",
    "value": "0.75rem",
    "cssVariable": "--csn-ref-radius-lg",
    "description": "Large corner radius reference."
  },
  {
    "name": "radius.full",
    "type": "dimension",
    "value": "9999px",
    "cssVariable": "--csn-ref-radius-full",
    "description": "Pill and circular radius reference."
  },
  {
    "name": "border.width.0",
    "type": "dimension",
    "value": "0",
    "cssVariable": "--csn-ref-border-width-0",
    "description": "No-border width reference."
  },
  {
    "name": "border.width.1",
    "type": "dimension",
    "value": "1px",
    "cssVariable": "--csn-ref-border-width-1",
    "description": "Default border width reference."
  },
  {
    "name": "border.width.2",
    "type": "dimension",
    "value": "2px",
    "cssVariable": "--csn-ref-border-width-2",
    "description": "Strong border width reference."
  },
  {
    "name": "font.family.sans",
    "type": "font-family",
    "value": "ui-sans-serif, system-ui, sans-serif",
    "cssVariable": "--csn-ref-font-family-sans",
    "description": "System-oriented sans-serif font stack."
  },
  {
    "name": "font.family.mono",
    "type": "font-family",
    "value": "ui-monospace, SFMono-Regular, Consolas, monospace",
    "cssVariable": "--csn-ref-font-family-mono",
    "description": "System-oriented monospace font stack."
  },
  {
    "name": "font.size.xs",
    "type": "font-size",
    "value": "0.75rem",
    "cssVariable": "--csn-ref-font-size-xs",
    "description": "Extra-small text size reference."
  },
  {
    "name": "font.size.sm",
    "type": "font-size",
    "value": "0.875rem",
    "cssVariable": "--csn-ref-font-size-sm",
    "description": "Small text size reference."
  },
  {
    "name": "font.size.md",
    "type": "font-size",
    "value": "1rem",
    "cssVariable": "--csn-ref-font-size-md",
    "description": "Body text size reference."
  },
  {
    "name": "font.size.lg",
    "type": "font-size",
    "value": "1.125rem",
    "cssVariable": "--csn-ref-font-size-lg",
    "description": "Large text size reference."
  },
  {
    "name": "font.size.xl",
    "type": "font-size",
    "value": "1.25rem",
    "cssVariable": "--csn-ref-font-size-xl",
    "description": "Extra-large text size reference."
  },
  {
    "name": "font.size.2xl",
    "type": "font-size",
    "value": "1.5rem",
    "cssVariable": "--csn-ref-font-size-2xl",
    "description": "Heading text size reference."
  },
  {
    "name": "font.size.3xl",
    "type": "font-size",
    "value": "1.875rem",
    "cssVariable": "--csn-ref-font-size-3xl",
    "description": "Display text size reference."
  },
  {
    "name": "font.weight.regular",
    "type": "font-weight",
    "value": 400,
    "cssVariable": "--csn-ref-font-weight-regular",
    "description": "Regular font weight reference."
  },
  {
    "name": "font.weight.medium",
    "type": "font-weight",
    "value": 500,
    "cssVariable": "--csn-ref-font-weight-medium",
    "description": "Medium font weight reference."
  },
  {
    "name": "font.weight.semibold",
    "type": "font-weight",
    "value": 600,
    "cssVariable": "--csn-ref-font-weight-semibold",
    "description": "Semibold font weight reference."
  },
  {
    "name": "font.weight.bold",
    "type": "font-weight",
    "value": 700,
    "cssVariable": "--csn-ref-font-weight-bold",
    "description": "Bold font weight reference."
  },
  {
    "name": "line-height.tight",
    "type": "line-height",
    "value": 1.25,
    "cssVariable": "--csn-ref-line-height-tight",
    "description": "Tight line-height reference."
  },
  {
    "name": "line-height.normal",
    "type": "line-height",
    "value": 1.5,
    "cssVariable": "--csn-ref-line-height-normal",
    "description": "Default line-height reference."
  },
  {
    "name": "line-height.relaxed",
    "type": "line-height",
    "value": 1.75,
    "cssVariable": "--csn-ref-line-height-relaxed",
    "description": "Relaxed line-height reference."
  },
  {
    "name": "shadow.none",
    "type": "shadow",
    "value": "none",
    "cssVariable": "--csn-ref-shadow-none",
    "description": "No-elevation shadow reference."
  },
  {
    "name": "shadow.sm",
    "type": "shadow",
    "value": "0 1px 2px rgb(15 23 42 / 0.08)",
    "cssVariable": "--csn-ref-shadow-sm",
    "description": "Low-elevation shadow reference."
  },
  {
    "name": "shadow.md",
    "type": "shadow",
    "value": "0 4px 12px rgb(15 23 42 / 0.12)",
    "cssVariable": "--csn-ref-shadow-md",
    "description": "Medium-elevation shadow reference."
  },
  {
    "name": "shadow.lg",
    "type": "shadow",
    "value": "0 12px 32px rgb(15 23 42 / 0.18)",
    "cssVariable": "--csn-ref-shadow-lg",
    "description": "High-elevation shadow reference."
  },
  {
    "name": "duration.instant",
    "type": "duration",
    "value": "0ms",
    "cssVariable": "--csn-ref-duration-instant",
    "description": "No-motion duration reference."
  },
  {
    "name": "duration.fast",
    "type": "duration",
    "value": "120ms",
    "cssVariable": "--csn-ref-duration-fast",
    "description": "Fast motion duration reference."
  },
  {
    "name": "duration.standard",
    "type": "duration",
    "value": "200ms",
    "cssVariable": "--csn-ref-duration-standard",
    "description": "Standard motion duration reference."
  },
  {
    "name": "duration.slow",
    "type": "duration",
    "value": "320ms",
    "cssVariable": "--csn-ref-duration-slow",
    "description": "Slow motion duration reference."
  },
  {
    "name": "easing.standard",
    "type": "easing",
    "value": "cubic-bezier(0.2, 0, 0, 1)",
    "cssVariable": "--csn-ref-easing-standard",
    "description": "Standard motion easing reference."
  },
  {
    "name": "easing.emphasized",
    "type": "easing",
    "value": "cubic-bezier(0.2, 0, 0, 1.2)",
    "cssVariable": "--csn-ref-easing-emphasized",
    "description": "Emphasized motion easing reference."
  },
  {
    "name": "opacity.50",
    "type": "number",
    "value": 0.5,
    "cssVariable": "--csn-ref-opacity-50",
    "description": "Half-opacity reference."
  },
  {
    "name": "density.comfortable",
    "type": "number",
    "value": 1,
    "cssVariable": "--csn-ref-density-comfortable",
    "description": "Comfortable density scale reference."
  },
  {
    "name": "density.compact",
    "type": "number",
    "value": 0.875,
    "cssVariable": "--csn-ref-density-compact",
    "description": "Compact density scale reference."
  },
  {
    "name": "z-index.base",
    "type": "z-index",
    "value": 0,
    "cssVariable": "--csn-ref-z-index-base",
    "description": "Base stacking reference."
  },
  {
    "name": "z-index.overlay",
    "type": "z-index",
    "value": 1000,
    "cssVariable": "--csn-ref-z-index-overlay",
    "description": "Overlay stacking reference."
  },
  {
    "name": "z-index.modal",
    "type": "z-index",
    "value": 1100,
    "cssVariable": "--csn-ref-z-index-modal",
    "description": "Modal stacking reference."
  },
  {
    "name": "z-index.toast",
    "type": "z-index",
    "value": 1200,
    "cssVariable": "--csn-ref-z-index-toast",
    "description": "Toast stacking reference."
  }
] as const satisfies readonly PrimitiveTokenDefinition[];
export const semanticTokens = [
  {
    "name": "surface.canvas",
    "type": "color",
    "reference": "color.neutral.0",
    "cssVariable": "--csn-surface-canvas",
    "description": "Application canvas surface."
  },
  {
    "name": "surface.subtle",
    "type": "color",
    "reference": "color.neutral.50",
    "cssVariable": "--csn-surface-subtle",
    "description": "Subtle grouped surface."
  },
  {
    "name": "surface.raised",
    "type": "color",
    "reference": "color.neutral.0",
    "cssVariable": "--csn-surface-raised",
    "description": "Raised content surface."
  },
  {
    "name": "surface.inverse",
    "type": "color",
    "reference": "color.neutral.900",
    "cssVariable": "--csn-surface-inverse",
    "description": "High-contrast inverse surface."
  },
  {
    "name": "text.primary",
    "type": "color",
    "reference": "color.neutral.900",
    "cssVariable": "--csn-text-primary",
    "description": "Primary content text."
  },
  {
    "name": "text.secondary",
    "type": "color",
    "reference": "color.neutral.700",
    "cssVariable": "--csn-text-secondary",
    "description": "Secondary content text."
  },
  {
    "name": "text.muted",
    "type": "color",
    "reference": "color.neutral.500",
    "cssVariable": "--csn-text-muted",
    "description": "Muted supporting text."
  },
  {
    "name": "text.inverse",
    "type": "color",
    "reference": "color.neutral.0",
    "cssVariable": "--csn-text-inverse",
    "description": "Text on inverse surfaces."
  },
  {
    "name": "border.default",
    "type": "color",
    "reference": "color.neutral.200",
    "cssVariable": "--csn-border-default",
    "description": "Default boundary color."
  },
  {
    "name": "border.strong",
    "type": "color",
    "reference": "color.neutral.300",
    "cssVariable": "--csn-border-strong",
    "description": "Emphasized boundary color."
  },
  {
    "name": "interactive.primary",
    "type": "color",
    "reference": "color.brand.500",
    "cssVariable": "--csn-interactive-primary",
    "description": "Primary interactive color."
  },
  {
    "name": "interactive.primary-hover",
    "type": "color",
    "reference": "color.brand.600",
    "cssVariable": "--csn-interactive-primary-hover",
    "description": "Primary interactive hover color."
  },
  {
    "name": "interactive.primary-active",
    "type": "color",
    "reference": "color.brand.700",
    "cssVariable": "--csn-interactive-primary-active",
    "description": "Primary interactive active color."
  },
  {
    "name": "interactive.on-primary",
    "type": "color",
    "reference": "color.neutral.0",
    "cssVariable": "--csn-interactive-on-primary",
    "description": "Content color on primary interaction surfaces."
  },
  {
    "name": "interactive.secondary",
    "type": "color",
    "reference": "color.neutral.100",
    "cssVariable": "--csn-interactive-secondary",
    "description": "Secondary interactive surface color."
  },
  {
    "name": "interactive.secondary-hover",
    "type": "color",
    "reference": "color.neutral.200",
    "cssVariable": "--csn-interactive-secondary-hover",
    "description": "Secondary interactive hover color."
  },
  {
    "name": "focus.ring",
    "type": "color",
    "reference": "color.brand.500",
    "cssVariable": "--csn-focus-ring",
    "description": "Visible focus indicator color."
  },
  {
    "name": "status.danger",
    "type": "color",
    "reference": "color.red.500",
    "cssVariable": "--csn-status-danger",
    "description": "Danger status foreground color."
  },
  {
    "name": "status.danger-surface",
    "type": "color",
    "reference": "color.red.50",
    "cssVariable": "--csn-status-danger-surface",
    "description": "Danger status surface color."
  },
  {
    "name": "status.success",
    "type": "color",
    "reference": "color.green.500",
    "cssVariable": "--csn-status-success",
    "description": "Success status foreground color."
  },
  {
    "name": "status.success-surface",
    "type": "color",
    "reference": "color.green.50",
    "cssVariable": "--csn-status-success-surface",
    "description": "Success status surface color."
  },
  {
    "name": "status.warning",
    "type": "color",
    "reference": "color.amber.500",
    "cssVariable": "--csn-status-warning",
    "description": "Warning status foreground color."
  },
  {
    "name": "status.warning-surface",
    "type": "color",
    "reference": "color.amber.50",
    "cssVariable": "--csn-status-warning-surface",
    "description": "Warning status surface color."
  },
  {
    "name": "spacing.control-inline",
    "type": "dimension",
    "reference": "space.3",
    "cssVariable": "--csn-spacing-control-inline",
    "description": "Default inline control spacing."
  },
  {
    "name": "spacing.control-block",
    "type": "dimension",
    "reference": "space.2",
    "cssVariable": "--csn-spacing-control-block",
    "description": "Default block control spacing."
  },
  {
    "name": "spacing.content-gap",
    "type": "dimension",
    "reference": "space.4",
    "cssVariable": "--csn-spacing-content-gap",
    "description": "Default content gap."
  },
  {
    "name": "spacing.layout-gutter",
    "type": "dimension",
    "reference": "space.6",
    "cssVariable": "--csn-spacing-layout-gutter",
    "description": "Default layout gutter."
  },
  {
    "name": "spacing.layout-section",
    "type": "dimension",
    "reference": "space.12",
    "cssVariable": "--csn-spacing-layout-section",
    "description": "Default layout section spacing."
  },
  {
    "name": "radius.control",
    "type": "dimension",
    "reference": "radius.md",
    "cssVariable": "--csn-radius-control",
    "description": "Default control corner radius."
  },
  {
    "name": "radius.surface",
    "type": "dimension",
    "reference": "radius.lg",
    "cssVariable": "--csn-radius-surface",
    "description": "Default surface corner radius."
  },
  {
    "name": "radius.pill",
    "type": "dimension",
    "reference": "radius.full",
    "cssVariable": "--csn-radius-pill",
    "description": "Pill-shaped corner radius."
  },
  {
    "name": "border-width.default",
    "type": "dimension",
    "reference": "border.width.1",
    "cssVariable": "--csn-border-width-default",
    "description": "Default semantic border width."
  },
  {
    "name": "border-width.strong",
    "type": "dimension",
    "reference": "border.width.2",
    "cssVariable": "--csn-border-width-strong",
    "description": "Strong semantic border width."
  },
  {
    "name": "typography.body-family",
    "type": "font-family",
    "reference": "font.family.sans",
    "cssVariable": "--csn-typography-body-family",
    "description": "Body text font family."
  },
  {
    "name": "typography.code-family",
    "type": "font-family",
    "reference": "font.family.mono",
    "cssVariable": "--csn-typography-code-family",
    "description": "Code text font family."
  },
  {
    "name": "typography.body-size",
    "type": "font-size",
    "reference": "font.size.md",
    "cssVariable": "--csn-typography-body-size",
    "description": "Body text font size."
  },
  {
    "name": "typography.small-size",
    "type": "font-size",
    "reference": "font.size.sm",
    "cssVariable": "--csn-typography-small-size",
    "description": "Supporting text font size."
  },
  {
    "name": "typography.heading-size",
    "type": "font-size",
    "reference": "font.size.2xl",
    "cssVariable": "--csn-typography-heading-size",
    "description": "Default heading font size."
  },
  {
    "name": "typography.body-weight",
    "type": "font-weight",
    "reference": "font.weight.regular",
    "cssVariable": "--csn-typography-body-weight",
    "description": "Body text font weight."
  },
  {
    "name": "typography.emphasis-weight",
    "type": "font-weight",
    "reference": "font.weight.medium",
    "cssVariable": "--csn-typography-emphasis-weight",
    "description": "Emphasized text font weight."
  },
  {
    "name": "typography.heading-weight",
    "type": "font-weight",
    "reference": "font.weight.semibold",
    "cssVariable": "--csn-typography-heading-weight",
    "description": "Heading font weight."
  },
  {
    "name": "typography.body-line-height",
    "type": "line-height",
    "reference": "line-height.normal",
    "cssVariable": "--csn-typography-body-line-height",
    "description": "Body text line height."
  },
  {
    "name": "typography.heading-line-height",
    "type": "line-height",
    "reference": "line-height.tight",
    "cssVariable": "--csn-typography-heading-line-height",
    "description": "Heading line height."
  },
  {
    "name": "elevation.surface",
    "type": "shadow",
    "reference": "shadow.sm",
    "cssVariable": "--csn-elevation-surface",
    "description": "Raised surface elevation."
  },
  {
    "name": "elevation.overlay",
    "type": "shadow",
    "reference": "shadow.lg",
    "cssVariable": "--csn-elevation-overlay",
    "description": "Overlay surface elevation."
  },
  {
    "name": "motion.duration-fast",
    "type": "duration",
    "reference": "duration.fast",
    "cssVariable": "--csn-motion-duration-fast",
    "description": "Fast semantic motion duration."
  },
  {
    "name": "motion.duration-standard",
    "type": "duration",
    "reference": "duration.standard",
    "cssVariable": "--csn-motion-duration-standard",
    "description": "Standard semantic motion duration."
  },
  {
    "name": "motion.duration-slow",
    "type": "duration",
    "reference": "duration.slow",
    "cssVariable": "--csn-motion-duration-slow",
    "description": "Slow semantic motion duration."
  },
  {
    "name": "motion.easing-standard",
    "type": "easing",
    "reference": "easing.standard",
    "cssVariable": "--csn-motion-easing-standard",
    "description": "Standard semantic motion easing."
  },
  {
    "name": "motion.easing-emphasized",
    "type": "easing",
    "reference": "easing.emphasized",
    "cssVariable": "--csn-motion-easing-emphasized",
    "description": "Emphasized semantic motion easing."
  },
  {
    "name": "opacity.disabled",
    "type": "number",
    "reference": "opacity.50",
    "cssVariable": "--csn-opacity-disabled",
    "description": "Disabled-content opacity."
  },
  {
    "name": "density.scale",
    "type": "number",
    "reference": "density.comfortable",
    "cssVariable": "--csn-density-scale",
    "description": "Default density scale."
  },
  {
    "name": "stacking.base",
    "type": "z-index",
    "reference": "z-index.base",
    "cssVariable": "--csn-stacking-base",
    "description": "Base content stacking level."
  },
  {
    "name": "stacking.overlay",
    "type": "z-index",
    "reference": "z-index.overlay",
    "cssVariable": "--csn-stacking-overlay",
    "description": "Overlay stacking level."
  },
  {
    "name": "stacking.modal",
    "type": "z-index",
    "reference": "z-index.modal",
    "cssVariable": "--csn-stacking-modal",
    "description": "Modal stacking level."
  },
  {
    "name": "stacking.toast",
    "type": "z-index",
    "reference": "z-index.toast",
    "cssVariable": "--csn-stacking-toast",
    "description": "Toast stacking level."
  }
] as const satisfies readonly SemanticTokenDefinition[];
export const componentTokens = [
  {
    "component": "Button",
    "name": "button.background",
    "type": "color",
    "reference": "interactive.secondary",
    "cssVariable": "--csn-button-background",
    "description": "Default Button background color."
  },
  {
    "component": "Button",
    "name": "button.foreground",
    "type": "color",
    "reference": "text.primary",
    "cssVariable": "--csn-button-foreground",
    "description": "Default Button foreground color."
  },
  {
    "component": "Button",
    "name": "button.border",
    "type": "color",
    "reference": "border.strong",
    "cssVariable": "--csn-button-border",
    "description": "Default Button border color."
  },
  {
    "component": "Button",
    "name": "button.focus-ring",
    "type": "color",
    "reference": "focus.ring",
    "cssVariable": "--csn-button-focus-ring",
    "description": "Button focus indicator color."
  },
  {
    "component": "Button",
    "name": "button.padding-inline",
    "type": "dimension",
    "reference": "spacing.control-inline",
    "cssVariable": "--csn-button-padding-inline",
    "description": "Default Button inline padding."
  },
  {
    "component": "Button",
    "name": "button.padding-block",
    "type": "dimension",
    "reference": "spacing.control-block",
    "cssVariable": "--csn-button-padding-block",
    "description": "Default Button block padding."
  },
  {
    "component": "Button",
    "name": "button.gap",
    "type": "dimension",
    "reference": "spacing.control-block",
    "cssVariable": "--csn-button-gap",
    "description": "Gap between Button content slots."
  },
  {
    "component": "Button",
    "name": "button.radius",
    "type": "dimension",
    "reference": "radius.control",
    "cssVariable": "--csn-button-radius",
    "description": "Default Button corner radius."
  },
  {
    "component": "Button",
    "name": "button.font-size",
    "type": "font-size",
    "reference": "typography.body-size",
    "cssVariable": "--csn-button-font-size",
    "description": "Default Button font size."
  },
  {
    "component": "Button",
    "name": "button.font-weight",
    "type": "font-weight",
    "reference": "typography.emphasis-weight",
    "cssVariable": "--csn-button-font-weight",
    "description": "Button label font weight."
  },
  {
    "component": "Button",
    "name": "button.line-height",
    "type": "line-height",
    "reference": "typography.body-line-height",
    "cssVariable": "--csn-button-line-height",
    "description": "Button label line height."
  },
  {
    "component": "Button",
    "name": "button.min-block-size",
    "type": "dimension",
    "reference": "space.12",
    "cssVariable": "--csn-button-min-block-size",
    "description": "Default Button minimum block size."
  },
  {
    "component": "Button",
    "name": "button.disabled-opacity",
    "type": "number",
    "reference": "opacity.disabled",
    "cssVariable": "--csn-button-disabled-opacity",
    "description": "Button disabled-state opacity."
  },
  {
    "component": "Button",
    "name": "button.transition-duration",
    "type": "duration",
    "reference": "motion.duration-fast",
    "cssVariable": "--csn-button-transition-duration",
    "description": "Button interaction transition duration."
  },
  {
    "component": "Button",
    "name": "button.icon-size",
    "type": "font-size",
    "reference": "typography.body-size",
    "cssVariable": "--csn-button-icon-size",
    "description": "Default Button decorative content size."
  },
  {
    "component": "Icon",
    "name": "icon.size",
    "type": "font-size",
    "reference": "typography.body-size",
    "cssVariable": "--csn-icon-size",
    "description": "Default Icon box size."
  },
  {
    "component": "Icon",
    "name": "icon.color",
    "type": "color",
    "reference": "text.primary",
    "cssVariable": "--csn-icon-color",
    "description": "Default Icon foreground color."
  },
  {
    "component": "SVGIcon",
    "name": "svg-icon.size",
    "type": "font-size",
    "reference": "typography.body-size",
    "cssVariable": "--csn-svg-icon-size",
    "description": "Default SVGIcon box size."
  },
  {
    "component": "SVGIcon",
    "name": "svg-icon.color",
    "type": "color",
    "reference": "text.primary",
    "cssVariable": "--csn-svg-icon-color",
    "description": "Default SVGIcon foreground color."
  },
  {
    "component": "Typography",
    "name": "typography.font-family",
    "type": "font-family",
    "reference": "typography.body-family",
    "cssVariable": "--csn-typography-font-family",
    "description": "Default Typography font family."
  },
  {
    "component": "Typography",
    "name": "typography.font-size",
    "type": "font-size",
    "reference": "typography.body-size",
    "cssVariable": "--csn-typography-font-size",
    "description": "Default Typography font size."
  },
  {
    "component": "Typography",
    "name": "typography.font-weight",
    "type": "font-weight",
    "reference": "typography.body-weight",
    "cssVariable": "--csn-typography-font-weight",
    "description": "Default Typography font weight."
  },
  {
    "component": "Typography",
    "name": "typography.line-height",
    "type": "line-height",
    "reference": "typography.body-line-height",
    "cssVariable": "--csn-typography-line-height",
    "description": "Default Typography line height."
  },
  {
    "component": "Typography",
    "name": "typography.color",
    "type": "color",
    "reference": "text.primary",
    "cssVariable": "--csn-typography-color",
    "description": "Default Typography foreground color."
  },
  {
    "component": "Label",
    "name": "label.font-family",
    "type": "font-family",
    "reference": "typography.body-family",
    "cssVariable": "--csn-label-font-family",
    "description": "Default Label font family."
  },
  {
    "component": "Label",
    "name": "label.font-size",
    "type": "font-size",
    "reference": "typography.body-size",
    "cssVariable": "--csn-label-font-size",
    "description": "Default Label font size."
  },
  {
    "component": "Label",
    "name": "label.font-weight",
    "type": "font-weight",
    "reference": "typography.emphasis-weight",
    "cssVariable": "--csn-label-font-weight",
    "description": "Label caption font weight."
  },
  {
    "component": "Label",
    "name": "label.line-height",
    "type": "line-height",
    "reference": "typography.body-line-height",
    "cssVariable": "--csn-label-line-height",
    "description": "Label caption line height."
  },
  {
    "component": "Label",
    "name": "label.color",
    "type": "color",
    "reference": "text.primary",
    "cssVariable": "--csn-label-color",
    "description": "Default Label foreground color."
  },
  {
    "component": "Label",
    "name": "label.requirement-color",
    "type": "color",
    "reference": "text.muted",
    "cssVariable": "--csn-label-requirement-color",
    "description": "Label requirement marker color."
  },
  {
    "component": "Label",
    "name": "label.invalid-color",
    "type": "color",
    "reference": "status.danger",
    "cssVariable": "--csn-label-invalid-color",
    "description": "Label foreground color when the editor is invalid."
  },
  {
    "component": "Label",
    "name": "label.disabled-opacity",
    "type": "number",
    "reference": "opacity.disabled",
    "cssVariable": "--csn-label-disabled-opacity",
    "description": "Label opacity when the editor is disabled."
  },
  {
    "component": "Label",
    "name": "label.gap",
    "type": "dimension",
    "reference": "space.1",
    "cssVariable": "--csn-label-gap",
    "description": "Gap between the Label caption and its requirement marker."
  }
] as const satisfies readonly ComponentTokenDefinition[];
export const tokenCssVariables = {
  "color.neutral.0": "--csn-ref-color-neutral-0",
  "color.neutral.50": "--csn-ref-color-neutral-50",
  "color.neutral.100": "--csn-ref-color-neutral-100",
  "color.neutral.200": "--csn-ref-color-neutral-200",
  "color.neutral.300": "--csn-ref-color-neutral-300",
  "color.neutral.500": "--csn-ref-color-neutral-500",
  "color.neutral.700": "--csn-ref-color-neutral-700",
  "color.neutral.900": "--csn-ref-color-neutral-900",
  "color.neutral.1000": "--csn-ref-color-neutral-1000",
  "color.brand.50": "--csn-ref-color-brand-50",
  "color.brand.100": "--csn-ref-color-brand-100",
  "color.brand.500": "--csn-ref-color-brand-500",
  "color.brand.600": "--csn-ref-color-brand-600",
  "color.brand.700": "--csn-ref-color-brand-700",
  "color.red.50": "--csn-ref-color-red-50",
  "color.red.500": "--csn-ref-color-red-500",
  "color.red.700": "--csn-ref-color-red-700",
  "color.green.50": "--csn-ref-color-green-50",
  "color.green.500": "--csn-ref-color-green-500",
  "color.green.700": "--csn-ref-color-green-700",
  "color.amber.50": "--csn-ref-color-amber-50",
  "color.amber.500": "--csn-ref-color-amber-500",
  "color.amber.700": "--csn-ref-color-amber-700",
  "space.0": "--csn-ref-space-0",
  "space.1": "--csn-ref-space-1",
  "space.2": "--csn-ref-space-2",
  "space.3": "--csn-ref-space-3",
  "space.4": "--csn-ref-space-4",
  "space.5": "--csn-ref-space-5",
  "space.6": "--csn-ref-space-6",
  "space.8": "--csn-ref-space-8",
  "space.10": "--csn-ref-space-10",
  "space.12": "--csn-ref-space-12",
  "radius.none": "--csn-ref-radius-none",
  "radius.sm": "--csn-ref-radius-sm",
  "radius.md": "--csn-ref-radius-md",
  "radius.lg": "--csn-ref-radius-lg",
  "radius.full": "--csn-ref-radius-full",
  "border.width.0": "--csn-ref-border-width-0",
  "border.width.1": "--csn-ref-border-width-1",
  "border.width.2": "--csn-ref-border-width-2",
  "font.family.sans": "--csn-ref-font-family-sans",
  "font.family.mono": "--csn-ref-font-family-mono",
  "font.size.xs": "--csn-ref-font-size-xs",
  "font.size.sm": "--csn-ref-font-size-sm",
  "font.size.md": "--csn-ref-font-size-md",
  "font.size.lg": "--csn-ref-font-size-lg",
  "font.size.xl": "--csn-ref-font-size-xl",
  "font.size.2xl": "--csn-ref-font-size-2xl",
  "font.size.3xl": "--csn-ref-font-size-3xl",
  "font.weight.regular": "--csn-ref-font-weight-regular",
  "font.weight.medium": "--csn-ref-font-weight-medium",
  "font.weight.semibold": "--csn-ref-font-weight-semibold",
  "font.weight.bold": "--csn-ref-font-weight-bold",
  "line-height.tight": "--csn-ref-line-height-tight",
  "line-height.normal": "--csn-ref-line-height-normal",
  "line-height.relaxed": "--csn-ref-line-height-relaxed",
  "shadow.none": "--csn-ref-shadow-none",
  "shadow.sm": "--csn-ref-shadow-sm",
  "shadow.md": "--csn-ref-shadow-md",
  "shadow.lg": "--csn-ref-shadow-lg",
  "duration.instant": "--csn-ref-duration-instant",
  "duration.fast": "--csn-ref-duration-fast",
  "duration.standard": "--csn-ref-duration-standard",
  "duration.slow": "--csn-ref-duration-slow",
  "easing.standard": "--csn-ref-easing-standard",
  "easing.emphasized": "--csn-ref-easing-emphasized",
  "opacity.50": "--csn-ref-opacity-50",
  "density.comfortable": "--csn-ref-density-comfortable",
  "density.compact": "--csn-ref-density-compact",
  "z-index.base": "--csn-ref-z-index-base",
  "z-index.overlay": "--csn-ref-z-index-overlay",
  "z-index.modal": "--csn-ref-z-index-modal",
  "z-index.toast": "--csn-ref-z-index-toast",
  "surface.canvas": "--csn-surface-canvas",
  "surface.subtle": "--csn-surface-subtle",
  "surface.raised": "--csn-surface-raised",
  "surface.inverse": "--csn-surface-inverse",
  "text.primary": "--csn-text-primary",
  "text.secondary": "--csn-text-secondary",
  "text.muted": "--csn-text-muted",
  "text.inverse": "--csn-text-inverse",
  "border.default": "--csn-border-default",
  "border.strong": "--csn-border-strong",
  "interactive.primary": "--csn-interactive-primary",
  "interactive.primary-hover": "--csn-interactive-primary-hover",
  "interactive.primary-active": "--csn-interactive-primary-active",
  "interactive.on-primary": "--csn-interactive-on-primary",
  "interactive.secondary": "--csn-interactive-secondary",
  "interactive.secondary-hover": "--csn-interactive-secondary-hover",
  "focus.ring": "--csn-focus-ring",
  "status.danger": "--csn-status-danger",
  "status.danger-surface": "--csn-status-danger-surface",
  "status.success": "--csn-status-success",
  "status.success-surface": "--csn-status-success-surface",
  "status.warning": "--csn-status-warning",
  "status.warning-surface": "--csn-status-warning-surface",
  "spacing.control-inline": "--csn-spacing-control-inline",
  "spacing.control-block": "--csn-spacing-control-block",
  "spacing.content-gap": "--csn-spacing-content-gap",
  "spacing.layout-gutter": "--csn-spacing-layout-gutter",
  "spacing.layout-section": "--csn-spacing-layout-section",
  "radius.control": "--csn-radius-control",
  "radius.surface": "--csn-radius-surface",
  "radius.pill": "--csn-radius-pill",
  "border-width.default": "--csn-border-width-default",
  "border-width.strong": "--csn-border-width-strong",
  "typography.body-family": "--csn-typography-body-family",
  "typography.code-family": "--csn-typography-code-family",
  "typography.body-size": "--csn-typography-body-size",
  "typography.small-size": "--csn-typography-small-size",
  "typography.heading-size": "--csn-typography-heading-size",
  "typography.body-weight": "--csn-typography-body-weight",
  "typography.emphasis-weight": "--csn-typography-emphasis-weight",
  "typography.heading-weight": "--csn-typography-heading-weight",
  "typography.body-line-height": "--csn-typography-body-line-height",
  "typography.heading-line-height": "--csn-typography-heading-line-height",
  "elevation.surface": "--csn-elevation-surface",
  "elevation.overlay": "--csn-elevation-overlay",
  "motion.duration-fast": "--csn-motion-duration-fast",
  "motion.duration-standard": "--csn-motion-duration-standard",
  "motion.duration-slow": "--csn-motion-duration-slow",
  "motion.easing-standard": "--csn-motion-easing-standard",
  "motion.easing-emphasized": "--csn-motion-easing-emphasized",
  "opacity.disabled": "--csn-opacity-disabled",
  "density.scale": "--csn-density-scale",
  "stacking.base": "--csn-stacking-base",
  "stacking.overlay": "--csn-stacking-overlay",
  "stacking.modal": "--csn-stacking-modal",
  "stacking.toast": "--csn-stacking-toast",
  "button.background": "--csn-button-background",
  "button.foreground": "--csn-button-foreground",
  "button.border": "--csn-button-border",
  "button.focus-ring": "--csn-button-focus-ring",
  "button.padding-inline": "--csn-button-padding-inline",
  "button.padding-block": "--csn-button-padding-block",
  "button.gap": "--csn-button-gap",
  "button.radius": "--csn-button-radius",
  "button.font-size": "--csn-button-font-size",
  "button.font-weight": "--csn-button-font-weight",
  "button.line-height": "--csn-button-line-height",
  "button.min-block-size": "--csn-button-min-block-size",
  "button.disabled-opacity": "--csn-button-disabled-opacity",
  "button.transition-duration": "--csn-button-transition-duration",
  "button.icon-size": "--csn-button-icon-size",
  "icon.size": "--csn-icon-size",
  "icon.color": "--csn-icon-color",
  "svg-icon.size": "--csn-svg-icon-size",
  "svg-icon.color": "--csn-svg-icon-color",
  "typography.font-family": "--csn-typography-font-family",
  "typography.font-size": "--csn-typography-font-size",
  "typography.font-weight": "--csn-typography-font-weight",
  "typography.line-height": "--csn-typography-line-height",
  "typography.color": "--csn-typography-color",
  "label.font-family": "--csn-label-font-family",
  "label.font-size": "--csn-label-font-size",
  "label.font-weight": "--csn-label-font-weight",
  "label.line-height": "--csn-label-line-height",
  "label.color": "--csn-label-color",
  "label.requirement-color": "--csn-label-requirement-color",
  "label.invalid-color": "--csn-label-invalid-color",
  "label.disabled-opacity": "--csn-label-disabled-opacity",
  "label.gap": "--csn-label-gap"
} as const;
export const semanticTokenReferences = {
  "surface.canvas": "color.neutral.0",
  "surface.subtle": "color.neutral.50",
  "surface.raised": "color.neutral.0",
  "surface.inverse": "color.neutral.900",
  "text.primary": "color.neutral.900",
  "text.secondary": "color.neutral.700",
  "text.muted": "color.neutral.500",
  "text.inverse": "color.neutral.0",
  "border.default": "color.neutral.200",
  "border.strong": "color.neutral.300",
  "interactive.primary": "color.brand.500",
  "interactive.primary-hover": "color.brand.600",
  "interactive.primary-active": "color.brand.700",
  "interactive.on-primary": "color.neutral.0",
  "interactive.secondary": "color.neutral.100",
  "interactive.secondary-hover": "color.neutral.200",
  "focus.ring": "color.brand.500",
  "status.danger": "color.red.500",
  "status.danger-surface": "color.red.50",
  "status.success": "color.green.500",
  "status.success-surface": "color.green.50",
  "status.warning": "color.amber.500",
  "status.warning-surface": "color.amber.50",
  "spacing.control-inline": "space.3",
  "spacing.control-block": "space.2",
  "spacing.content-gap": "space.4",
  "spacing.layout-gutter": "space.6",
  "spacing.layout-section": "space.12",
  "radius.control": "radius.md",
  "radius.surface": "radius.lg",
  "radius.pill": "radius.full",
  "border-width.default": "border.width.1",
  "border-width.strong": "border.width.2",
  "typography.body-family": "font.family.sans",
  "typography.code-family": "font.family.mono",
  "typography.body-size": "font.size.md",
  "typography.small-size": "font.size.sm",
  "typography.heading-size": "font.size.2xl",
  "typography.body-weight": "font.weight.regular",
  "typography.emphasis-weight": "font.weight.medium",
  "typography.heading-weight": "font.weight.semibold",
  "typography.body-line-height": "line-height.normal",
  "typography.heading-line-height": "line-height.tight",
  "elevation.surface": "shadow.sm",
  "elevation.overlay": "shadow.lg",
  "motion.duration-fast": "duration.fast",
  "motion.duration-standard": "duration.standard",
  "motion.duration-slow": "duration.slow",
  "motion.easing-standard": "easing.standard",
  "motion.easing-emphasized": "easing.emphasized",
  "opacity.disabled": "opacity.50",
  "density.scale": "density.comfortable",
  "stacking.base": "z-index.base",
  "stacking.overlay": "z-index.overlay",
  "stacking.modal": "z-index.modal",
  "stacking.toast": "z-index.toast"
} as const;

export type PrimitiveTokenName = (typeof primitiveTokens)[number]['name'];
export type SemanticTokenName = (typeof semanticTokens)[number]['name'];
export type ComponentTokenName = (typeof componentTokens)[number]['name'];
export type TokenName = PrimitiveTokenName | SemanticTokenName | ComponentTokenName;
